#!/bin/bash

# Read .env file and convert to -e arguments
env_vars=$(cat .env | tr '\n' ' ')
env_vars=${env_vars// / -e }

docker run -e $env_vars -it --rm -p 3000:3000 --name munnizza-land munnizza-land